### ISSUE TITLE
Keycloak/SSO support, adding/removing users to SSO backend

### ISSUE THREAD

**Issue by olmari** [TampereHacklab/mulysa#262]
This can also add users to LDAP, when LDAP is backend for Keycloak realm, like Tampere will have. Main API finds here: https://www.keycloak.org/docs-api/11.0/rest-api/index.html

Will provide test system shortly.

**Comment by tswfi** [comment]
So how should this work on a higher level?

User registers in mulysa and mulysa creates the user in keycloak? And after that login happens against the sso there?

What about forgotten passwords, updating email address or deactivating the user?

Keycloak should probably be the master for user authentication...

**Comment by olmari** [comment]
> User registers in mulysa and mulysa creates the user in keycloak?

Yes.

> And after that login happens against the sso there?

Possibly, or propably the sanest option here. Needs some finer grain thoughts still.

> What about forgotten passwords, updating email address or deactivating the user?

If all auth is done against keycloak, then all these would go through or towards keycloak. PW resets and mail changes definately, deactivating would also be pushed by mulysa to keycloak with API.

> Keycloak should probably be the master for user authentication...

Likely, from the quick thoughts I'd say so too. Otherwise at the very least there would be so much more complicated things to think through that this would be indeed only sane option...

Some quick notions from for example Discourse SSO enabling:

```
Once enable_sso is set to true:

Clicking on login or avatar will, redirect you to /session/sso which in turn will redirect users to sso_url with a signed payload.
Users will not be allowed to “change password”. That field is removed from the user profile.
Users will no longer be able to use Discourse auth (username/password, google, etc)
```

**Comment by uumas** [comment]
You should use the current API docs: https://www.keycloak.org/docs-api/11.0/rest-api/index.html

mulysa should probably create a user in keycloak with a random password and send the user an email with the password and a link to https://sso.hacklab.fi/auth/realms/tampere/account (with that url configurable of course). The password should be created as temporary credential so that the user is prompted to change it on first login.

> Keycloak should probably be the master for user authentication...
If using LDAP as the database, all users should be created in LDAP. This can be achieved by either having mulysa write to ldap directly (mulysa has an ldap admin account) or by mulysa using the keycloak api and keycloak putting the user registrations to ldap (keycloak has an ldap admin account).

**Comment by tswfi** [comment]
If at all possible i would probably remove the ldap and use keycloak directly if at all possible in our systems. Anyway, that is another issue :)

**Comment by uumas** [comment]
If you want to login on local workstations you definitely want to have ldap. If it's just web-based stuff and other services which support sso, then keycloak should be enough.

**Comment by eimink** [comment]
Mylusa could be used as a backend in a way, that keycloack passes the authentication request to mylusa, which verifies if user has active membership and therefore is allowed to login to services. Alternate way would be to have a syncer running that keeps group information up-to-date so that user access management is automated based on membership status.

**Comment by olmari** [comment]
This is done with https://github.com/TampereHacklab/mulysa/pull/328 making mulysa an OIDC provider when configured.
