### ISSUE TITLE
Bank transaction retrieval automation using PSD2

### ISSUE THREAD

**Issue by VV-Soft** [TampereHacklab/mulysa#357]
It is possible to automate bank transaction retrieval using PSD2. There are companies that offer API for free ( I'm familiar with Nordigen ) 

Bank are required to give at least 90 days of past transactions and most banks allow authorization for 90 days to the future.

It would be possible to implement a feature where a person who has access to Hacklab account's online banking to authorize Mylusa to automatically retrieve transactions. Such an authorization would then have to be redone before it expires in 90 days in order to keep data flowing.

Nordigen also offers the ability to download actual transaction data for an account without any programming directly on their website (after free registration). This could be used for evaluating the usability of the data offered by Hacklabs bank before any programming is required.

**Comment by olmari** [comment]
This is something we have discussed earlier too that should be implemented, mostly because of Nordigen, Now we only need coders to actually do it :D

Nordigen would be first choice as it offers basically every (at least finnish) bank.

I know also OP (Osuuspankki) has API's available separately for "looking" an account and then "making payment" side, both with some few euro fee per month for customer, but that's still one bank only.

**Comment by olmari** [comment]
General broad issue with whole PSD2 is that basically private customers doesn't benefit squat from that, only other types of entitites... Whereas Nordigen offers that API stuff for free and make their money from customers that wants analyzing etc, this API is only byproduct, but quite happy byproduct if you ask me :)

**Comment by vranki** [comment]
Some kind of API is here: https://github.com/nordigen/nordigen-python

**Comment by tswfi** [comment]
https://github.com/TampereHacklab/mulysa/pull/397

**Comment by tswfi** [comment]
Done in #397 and deployed to production and looks like everything works great. Closing this.
