### ISSUE TITLE
Newly registered used shows "SUSPENDED" status

### ISSUE THREAD

**Issue by tswfi** [TampereHacklab/mulysa#85]
would probably be better to show a more user friendly message "your first payment has not yet been registered" or something

**Comment by vranki** [comment]
This is by design - newly registered users are not yet accepted as members so they can't pay for anything yet.

Suggested fix: if user has un-approved membership application, show special instructions for it instead of service status.

Something like: 
"Your application is being processed by the hacklab board. You will receive instructions in e-mail if your application is accepted".

**Comment by vranki** [comment]
User service status (other details) are now hidden if user has pending application.
